export const API_BASE = 'http://localhost:5000/api'

export const SEND_REGISTER_REQUEST = 'SEND_REGISTER_REQUEST';
export const SEND_REGISTER_SUCCESS = 'SEND_REGISTER_SUCCESS';
export const SEND_REGISTER_ERROR = 'SEND_REGISTER_ERROR';

export const SEND_LOGIN_REQUEST = 'SEND_LOGIN_REQUEST';
export const SEND_LOGIN_SUCCESS = 'SEND_LOGIN_SUCCESS';
export const SEND_LOGIN_ERROR = 'SEND_LOGIN_ERROR';

export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const PLACE_ORDER_REQUEST = 'PLACE_ORDER_REQUEST';