export const API_BASE = 'http://localhost:5000/api'

export const SEND_REGISTER_REQUEST = 'SEND_REGISTER_REQUEST';
export const SEND_REGISTER_SUCCESS = 'SEND_REGISTER_SUCCESS';
export const SEND_REGISTER_ERROR = 'SEND_REGISTER_ERROR';

export const SEND_LOGIN_REQUEST = 'SEND_LOGIN_REQUEST';
export const SEND_LOGIN_SUCCESS = 'SEND_LOGIN_SUCCESS';
export const SEND_LOGIN_ERROR = 'SEND_LOGIN_ERROR';

export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const PLACE_ORDER_REQUEST = 'PLACE_ORDER_REQUEST';

export const ADD_DROPDOWN_FILTER = 'ADD_DROPDOWN_FILTER';
export const CLEAR_DROPDOWN_FILTER= 'CLEAR_DROPDOWN_FILTER';

export const GET_ALL_REVIEWS = 'GET_ALL_REVIEWS';
export const GET_ALL_REVIEWS_SUCCESS = 'GET_ALL_REVIEWS_SUCCESS';
export const GET_ALL_REVIEWS_FAILED = 'GET_ALL_REVIEWS_FAILED';

export const ADD_A_REVIEW_REQUEST = 'ADD_A_REVIEW_REQUEST';
export const ADD_A_REVIEW_SUCCESS = 'ADD_A_REVIEW_SUCCESS';
export const ADD_A_REVIEW_FAILED = 'ADD_A_REVIEW_FAILED';

export const REGISTER_FOR_EVENT = 'REGISTER_FOR_EVENT';
export const REGISTER_FOR_EVENT_SUCCESS = 'REGISTER_FOR_EVENT_SUCCESS';
export const REGISTER_FOR_EVENT_FAILED = 'REGISTER_FOR_EVENT_FAILED';

export const SUBSCRIBE_EMAIL_REQUEST = 'SUBSCRIBE_EMAIL_REQUEST';
export const SUBSCRIBE_EMAIL_SUCCESS = 'SUBSCRIBE_EMAIL_SUCCESS';
export const SUBSCRIBE_EMAIL_REQUEST_FAILED = 'SUBSCRIBE_EMAIL_FAILED'